# .github/workflows/code_checks.yaml
name: Code_Checks

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.0']

    name: PHP ${{ matrix.php }} tests
    steps:
      # basically git clone
      -   uses: actions/checkout@v2

      # use PHP of specific version
      -   uses: shivammathur/setup-php@v1
          with:
            php-version: ${{ matrix.php }}
            coverage: none # disable xdebug, pcov
