# .github/workflows/code_checks.yaml
name: Code_Checks

on:
  pull_request: null
  push:
    branches:
      - main

jobs:
  rector-ci:
    runs-on: ubuntu-latest
    steps:
      -   uses: actions/checkout@v2
      -
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.3
          coverage: none # disable xdebug, pcov
      -   run: composer install --no-progress
      -   run: vendor/bin/rector process --dry-run --ansi
